stages:
  - test
  - docs
  - release

include:
  - project: 'ep/cloud/release/gitlab-ci-templates'
    ref: RE-83
    file: 'deploy-template-netlify.yaml'

before_script:
  - npm install

test:
  image: node:8
  stage: test
  script:
    - PIPELINE=true npm test

docs:
  stage: docs
  extends: .deploy
  variables:
    NETLIFY_DEPLOY_PATH: ./bin/folderStructure/docs
  only: 
    - master

publish: 
  image: node:8
  stage: release
  script: 
    - npx semantic-release