language: node_js
node_js: 
  - "10"

jobs: 
  include :
    - stage: test
      script: PIPELINE=true npm test _tests_
    - stage: publish
      if: branch = master
      script: npx semantic-release
