language: node_js
node_js: 
  - "10"

services:
  - docker

jobs: 
  include :
    - stage: test
      before_script: npm install netlify-cli
      script: PIPELINE=true npm test _tests_
      after_script: docker run --rm -it -v ${PWD}/allure-results:/allure-results -v ${PWD}/allure-report:/allure-report jackwilde/allure ./allure generate /allure-results -o /allure-report --clean
                    netlify deploy
    - stage: publish
      if: branch = master
      script: npx semantic-release
